### ISSUE TITLE
Нужно устанавливать howler и luxon через npm 

### ISSUE THREAD

**Issue by koretskyhub** [victoria369xx/bundle#4]
https://github.com/victoria369xx/bundle/blob/e8c2e482e17bd70ddf1acfa8ccc3e37facc8179e/homeworks/hw2/package.json#L27
Во 2ом дз у нас уже есть npm и мы можем библиотеки для нашего приложения поставить через npm
Поэтому файлики из 1го дз для этих библиотек можно удалить, установить в dependencies библиотек luxon и howler
И импортировать их уже вот так:
import { DateTime } from 'luxon'
import { Howl } from 'howler'

**Comment by victoria369xx** [comment]
переделала
